version: '3'

services:
  voice-changer-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./weights:/app/weights
      - ./logs:/app/logs
    environment:
      - MODEL_NAME=${MODEL_NAME:-titan}
      - PITCH_CHANGE=${PITCH_CHANGE:-0}
      - VOLUME_ENVELOPE=${VOLUME_ENVELOPE:-1.0}
      - INDEX_RATE=${INDEX_RATE:-0.0}
      - PITCH_EXTRACTION_ALGO=${PITCH_EXTRACTION_ALGO:-rmvpe}
      - GPU_INDEX=${GPU_INDEX:-0}
    restart: unless-stopped
    # For GPU support, uncomment the following lines:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]